### PR TITLE
Update ItemInit.java

### PR DESCRIPTION
**Pull request by KingRealzYT**
Made a Eternium Ingot

### CODE REVIEW

**Comment by Steaf23** [comment]
please finish the item before making a PR for it

**Review by DaRealTurtyWurty — CHANGES_REQUESTED** [review]
README.md, lang, item model, texture

**Comment by KingRealzYT** [comment]
@Steaf23 I should have hopefully completed everything needed

**Comment by KingRealzYT** [comment]
there now

**Review by DaRealTurtyWurty — APPROVED** [review]

**Pull request merged**
