### PR TITLE
Convert Tabs to (4) Spaces

### PR DESCRIPTION
**Pull request by MetalTurtle18**
To keep in line with the style guidelines for this project, java files should use 4 spaces instead of tabs.

This PR also fixes sounds.json (same as the change to this file in #33)

(There is no apple ingot in this PR. I will add that in a later one)

### CODE REVIEW

**Comment by MetalTurtle18** [comment]
The latest contribution to README.md includes a link that does not currently work. It should work once CONTRIBUTING.md is merged into this repository.

**Comment by DaRealTurtyWurty** [comment]
I can't really merge this until all of the other PRs have been merged. So unfortunately this could take a while.

**Comment by DaRealTurtyWurty** [comment]
It now also has a bunch of conflicts

**Comment by DaRealTurtyWurty** [comment]
Fixed in ca47d95

**Pull request closed without merging**
